import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from "@mui/material/styles";
import theme from '../theme';
import Header from "@/components/header/Header";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/utils/http";
import { ApolloClient } from "@apollo/client";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Inventory",
  description: "Generated by create next app",
};

const client = new ApolloClient({
  dataIdFromObject: (o) => o.id,
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description? metadata.description: ""} />
        <title>{typeof metadata.title === 'string' ? metadata.title : "Inventory"}</title>
        {/*<link rel="icon" href="/favicon.ico" />*/}

      </head>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <QueryClientProvider client={queryClient}>
              <Header sx={{marginBottom:'100px'}}/>
              {children}
            </QueryClientProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
